### ISSUE TITLE
Add cmake structure

### ISSUE THREAD

**Issue by BIRSAx2** [AlbaSat/OBC#1]
We need to remove the need for cubeIDE for the build process.
This is required for test environment automation.

**Comment by BIRSAx2** [comment]
Added draft of CMakeLists.txt. The project compiles successfully, but flashing the ELF file on the STM32 board is untested.
The current file is cluttered and needs refactoring.
Currently relying on FreeRTOS and FreeRTOS-FAT from the FreeRTOS repository using CMake's FetchContent.
@safesintesi is there any specific advantage in incorporating FreeRTOS and FAT as git submodules rather than fetching them using CMake? Open to insights and suggestions

**Comment by BIRSAx2** [comment]
I have refactored the CMakeLists.txt file. I can confirm that the project compiles successfully and flashes correctly to the STM32 Board. 
Please review the changes and let me know if there are any issues or further improvements needed. @gekoxyz 

PS: @safesintesi  If there are no issues with using CMake's FetchContent for FreeRTOS and FreeRTOS-FAT, I plan to remove the git submodules. This should simplify the project structure and make it easier to manage dependencies. If you agree with this approach, I will proceed with these changes and create a pull request for review. Please let me know your thoughts.

**Comment by safesintesi** [comment]
We used submodules because this is the de facto standard for integrating git repositories independently of the build system.

Cmake offers the possibility to use the FetchContent function (this means we need to update cmake dependency to 3.11 btw) to obtain the same result but this is specific to cmake builds.

STM32cubeIDE automatically generates Makefile(s) for build based on the files it can see inside the project and the .cproject file.

This means that if we remove submodules inside the repo in favor of FetchContent, the STM32cubeIDE fails.

Since we don't know who might come in the project in the future and what their knowledge level is, seems to me a harsh move to remove the standard and default build process described in every guide on the internet in favor of a (really nice) command line.
Keep in mind that we are NOT working on a cmake port to force everyone to build through CLI. You can make a headless build directly with STM32cubeIDE if this was what you want. The objective is to create a building process that doesn't require installing STM32cubeIDE for automatic testing with github actions.

With this in mind i would vote for keeping both paths. Maybe we should stick to a specific version (repo tag) of the libraries to keep submodules and FetchContent in sync.

**Comment by BIRSAx2** [comment]
I've considered your points, and I agree that maintaining both paths seems like a reasonable approach. 
I'll continue downloading dependencies through FetchContent for CMakeLists.txt builds, while retaining the submodules for STM32CubeIDE builds. 
Also, we need to align the versions between CMakeLists and git submodules– currently I’m using FreeRTOS-Kernel v10.6.2 tag and the latest commit for FreeRTOS-Plus-FAT.

**Comment by BIRSAx2** [comment]
Done #10
